const icons={home:'<path d="M3 11.5 12 4l9 7.5v8a1 1 0 0 1-1 1h-5v-6H9v6H4a1 1 0 0 1-1-1z"/>',map:'<circle cx="6" cy="18" r="2"/><circle cx="18" cy="6" r="2"/><path d="M7.5 16.5 16.5 7.5M8 6h4M6 8v4M12 18h6v-6"/>',repeat:'<path d="M20 7h-9a6 6 0 0 0-6 6v1M17 4l3 3-3 3M4 17h9a6 6 0 0 0 6-6v-1M7 20l-3-3 3-3"/>',chart:'<path d="M4 20V10M10 20V4M16 20v-7M22 20H2"/>',more:'<circle cx="5" cy="12" r="1"/><circle cx="12" cy="12" r="1"/><circle cx="19" cy="12" r="1"/>',message:'<path d="M20 15a4 4 0 0 1-4 4H8l-5 3 1.5-5A8 8 0 1 1 20 15z"/>',calendar:'<rect x="3" y="5" width="18" height="16" rx="3"/><path d="M8 3v4M16 3v4M3 10h18"/>',close:'<path d="m6 6 12 12M18 6 6 18"/>',arrow:'<path d="M19 12H5M11 18l-6-6 6-6"/>',bell:'<path d="M18 8a6 6 0 0 0-12 0c0 7-3 7-3 9h18c0-2-3-2-3-9M10 21h4"/>',book:'<path d="M4 5a3 3 0 0 1 3-2h13v16H7a3 3 0 0 0-3 2zM4 5v16M8 7h8"/>',check:'<path d="m5 12 4 4L19 6"/>',lock:'<rect x="5" y="10" width="14" height="11" rx="2"/><path d="M8 10V7a4 4 0 0 1 8 0v3"/>',scale:'<path d="M12 3v18M5 6h14M7 6l-4 7h8L7 6ZM17 6l-4 7h8l-4-7ZM8 21h8"/>',file:'<path d="M6 2h8l4 4v16H6zM14 2v5h5M9 13h6M9 17h6"/>',quiz:'<circle cx="12" cy="12" r="9"/><path d="M9.8 9a2.4 2.4 0 1 1 3 2.3c-.8.3-.8 1-.8 1.7M12 17h.01"/>',video:'<rect x="3" y="5" width="14" height="14" rx="2"/><path d="m17 10 4-2v8l-4-2z"/>',chevron:'<path d="m8 5 7 7-7 7"/>',spark:'<path d="m12 3 1.5 4.5L18 9l-4.5 1.5L12 15l-1.5-4.5L6 9l4.5-1.5z"/>',headset:'<path d="M4 14v-2a8 8 0 0 1 16 0v2M4 14h3v6H5a1 1 0 0 1-1-1zM20 14h-3v6h2a1 1 0 0 0 1-1z"/>',send:'<path d="m22 2-7 20-4-9-9-4zM22 2 11 13"/>',clock:'<circle cx="12" cy="12" r="9"/><path d="M12 7v6l4 2"/>',info:'<circle cx="12" cy="12" r="9"/><path d="M12 11v6M12 7h.01"/>',menu:'<path d="M4 7h16M4 12h16M4 17h16"/>',flag:'<path d="M5 22V3M5 4h11l-2 4 2 4H5"/>',moon:'<path d="M20 15.5A8.5 8.5 0 0 1 8.5 4 8.5 8.5 0 1 0 20 15.5Z"/>',sun:'<circle cx="12" cy="12" r="4"/><path d="M12 2v2M12 20v2M2 12h2M20 12h2"/>',play:'<path d="m8 5 11 7-11 7z"/>'};
const svg=n=>`<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${icons[n]||icons.book}</svg>`;
document.querySelectorAll('[data-icon]').forEach(el=>el.innerHTML=svg(el.dataset.icon));
const app=document.getElementById('app');
const subjects=[['حقوق مدنی',72],['حقوق تجارت',58],['آیین دادرسی مدنی',46],['حقوق جزا',64],['آیین دادرسی کیفری',39],['اصول فقه',75],['متون فقه',31],['حقوق اساسی',100]];
const subjectTopics=[['اشخاص و محجورین','اموال و مالکیت','قراردادها','مسئولیت مدنی'],['تاجر و اعمال تجاری','شرکت‌های تجاری','اسناد تجاری','ورشکستگی'],['صلاحیت دادگاه','دادخواست','دادرسی و رأی','طرق شکایت'],['عناصر جرم','مجازات‌ها','جرایم علیه اشخاص','جرایم علیه اموال'],['کشف و تعقیب','تحقیقات مقدماتی','دادگاه کیفری','اعتراض به آرا'],['الفاظ','اوامر و نواهی','عام و خاص','اصول عملیه'],['ترجمه فقهی','قواعد استنباط','عبارات منتخب','تحلیل متن'],['حقوق ملت','ساختار حکومت','قوای سه‌گانه','نظارت قانون اساسی']];
const chapterData=[{id:1,title:'فصل یک',sub:'شروع مسیر و مبانی'},{id:2,title:'فصل دو',sub:'تثبیت و توسعه'},{id:3,title:'فصل سه',sub:'تحلیل مواد'},{id:4,title:'فصل چهار',sub:'حل مسئله'},{id:5,title:'فصل پنج',sub:'مهارت تست'},{id:6,title:'مرور نیمه‌جامع اول',sub:'جمع‌بندی فصل‌های ۱ تا ۵',review:true},{id:7,title:'فصل شش',sub:'ورود به نیمه دوم'},{id:8,title:'فصل هفت',sub:'تکمیل مباحث'},{id:9,title:'فصل هشت',sub:'ترکیب مفاهیم'},{id:10,title:'فصل نه',sub:'آزمون‌محوری'},{id:11,title:'فصل ده',sub:'جمع‌بندی نهایی'},{id:12,title:'مرور نیمه‌جامع دوم',sub:'مرور کل دوره',review:true}];
const previewRoute=new URLSearchParams(location.search).get('preview');
const state={route:['roadmap','progress','reviews'].includes(previewRoute)?previewRoute:'home',chapter:null,subject:0,step:3,reviewed:[]};
const toFa=n=>String(n).replace(/\d/g,d=>'۰۱۲۳۴۵۶۷۸۹'[d]);
const course=()=>JSON.parse(localStorage.getItem('masirCourse')||'null')||{name:'وکالت ۱۴۰۵'};
const progress=()=>JSON.parse(localStorage.getItem('masirProgress')||'{"unlocked":2,"completed":[1]}');
const overall=()=>Math.round(subjects.reduce((a,s)=>a+s[1],0)/subjects.length);
function topbar(title,sub,back){return `<header class="topbar"><div class="topbar-side">${back?`<button class="icon-button" data-route="${back}" aria-label="بازگشت">${svg('arrow')}</button>`:''}</div><div class="topbar-copy"><h1>${title}</h1><p>${sub}</p></div><button class="icon-button" data-open-menu aria-label="منو">${svg('menu')}<i></i></button></header>`}
function home(){const p=overall();return `<div class="page">${topbar('مسیر مطالعاتی','آمادگی حرفه‌ای برای آزمون‌های حقوقی')}<section class="course-hero"><div class="legal-watermark">${svg('scale')}</div><div class="course-copy"><span class="section-kicker">دوره فعال</span><h2>${course().name}</h2><p>برنامه شخصی‌سازی‌شده بر اساس فصل و درس</p><button data-route="roadmap">ادامه مسیر ${svg('arrow')}</button></div><div class="progress-orbit" style="--p:${p*3.6}deg"><div><strong>${toFa(p)}٪</strong><small>پیشرفت کل</small></div></div></section><section class="compact-section"><div class="section-head"><div><span class="section-kicker">مرورهای آماده</span><h2>امروز چه چیزی را تثبیت می‌کنی؟</h2></div><button class="text-link" data-route="reviews">مشاهده همه</button></div><div class="review-grid">${reviewCards()}</div></section></div>`}
function reviewCards(){return [['حقوق مدنی','اشخاص و محجورین','۸ دقیقه'],['حقوق تجارت','اسناد تجاری','۱۲ دقیقه'],['اصول فقه','عام و خاص','۹ دقیقه']].map((r,i)=>`<article class="review-card"><span class="review-icon">${svg(i===2?'quiz':'repeat')}</span><div><small>${r[0]}</small><strong>${r[1]}</strong><p>${r[2]} · مرور فاصله‌دار</p></div><button aria-label="شروع مرور">${svg('play')}</button></article>`).join('')}
function roadmap(){const p=progress();return `<div class="page roadmap-page">${topbar('نقشه راه','تمام مسیر در یک نگاه','home')}<section class="roadmap-board"><div class="roadmap-intro"><div><span class="section-kicker">دوره ${course().name}</span><h2>از مبانی تا تسلط</h2></div><span>${toFa(p.completed.length)} مرحله تکمیل‌شده</span></div><div class="route-line">${chapterData.map(c=>{const done=p.completed.includes(c.id),active=c.id===p.unlocked,locked=c.id>p.unlocked;return `<button class="route-node ${done?'is-done':''} ${active?'is-current':''} ${locked?'is-locked':''} ${c.review?'is-review':''}" data-chapter="${c.id}" ${locked?'aria-disabled="true"':''}><span class="node-dot">${done?svg('check'):c.review?svg('repeat'):toFa(c.id>6?c.id-1:c.id)}</span><span class="node-copy"><strong>${c.title}</strong><small>${c.sub}</small></span>${locked?svg('lock'):svg('chevron')}</button>`}).join('')}<span class="finish-flag">${svg('flag')} پایان مسیر</span></div></section></div>`}
function previousAcademic(id){return id>6?id-2:id-1}
function reviewComplete(id){return JSON.parse(localStorage.getItem('masirReviews')||'[]').includes(id)}
function chapter(){const c=chapterData.find(x=>x.id===state.chapter);if(c.review)return comprehensive(c);const needsReview=c.id>1&&!reviewComplete(c.id);return `<div class="page chapter-page">${topbar(c.title,c.sub,'roadmap')}<section class="chapter-status"><div><span class="section-kicker">${needsReview?'دروازه ورود':'فصل فعال'}</span><h2>${needsReview?`ابتدا مرور فصل ${toFa(previousAcademic(c.id))}`:`محتوای ${c.title}`}</h2><p>${needsReview?'مرور و تست‌های فصل قبل را کامل کن تا محتوای تازه باز شود.':'درس را انتخاب کن؛ قدم‌های همان درس همین‌جا نمایش داده می‌شوند.'}</p></div><span class="chapter-pulse">${needsReview?svg('repeat'):svg('map')}</span></section>${needsReview?reviewGate(c):learningWorkspace(c)}</div>`}
function reviewGate(c){return `<section class="review-path"><div class="review-path-head"><span>مرحله ۱ از ۲</span><strong>نقشه مرور فصل ${toFa(previousAcademic(c.id))}</strong><small>${toFa(state.reviewed.length)} از ${toFa(6)} درس مرور شده</small></div><div class="review-checks">${subjects.slice(0,6).map((s,i)=>`<button class="review-check ${state.reviewed.includes(i)?'is-done':''}" data-review="${i}"><span>${state.reviewed.includes(i)?svg('check'):toFa(i+1)}</span><strong>${s[0]}</strong><small>${state.reviewed.includes(i)?'تکمیل شد':'مرور نکات و تست‌ها'}</small></button>`).join('')}</div><div class="unlock-preview"><span>${svg('lock')}</span><div><strong>مرحله ۲ · باز شدن کامل ${c.title}</strong><p>پس از تکمیل مرورها، درس‌ها و قدم‌های فصل خودکار باز می‌شوند.</p></div></div></section>`}
function learningWorkspace(c){const s=subjects[state.subject];return `<section class="learning-workspace"><div class="subject-picker"><div class="picker-head"><div><span class="section-kicker">درس و پیشرفت</span><h2>${c.title}</h2></div><span>مرحله ۲ از ۲</span></div><div class="subject-chips">${subjects.map((x,i)=>`<button class="subject-chip ${i===state.subject?'is-active':''}" data-subject="${i}"><span>${svg('scale')}</span><strong>${x[0]}</strong><small>${toFa(x[1])}٪</small></button>`).join('')}</div></div><div class="lesson-panel"><div class="lesson-head"><div><span class="section-kicker">مسیر درس انتخاب‌شده</span><h2>${s[0]}</h2><p>${subjectTopics[state.subject][0]} تا ${subjectTopics[state.subject][3]}</p></div><div class="mini-progress"><strong>${toFa(s[1])}٪</strong><i><b style="width:${s[1]}%"></b></i></div></div><div class="steps">${steps()}</div></div></section>`}
function steps(){const titles=['شناخت مبحث','تعاریف و ارکان','تحلیل مواد قانونی','نکات آزمونی','مثال‌های کاربردی','ویدیوی تکمیلی','جزوه جمع‌بندی','ارزیابی','مرور نهایی','تست‌خوانی'];return titles.map((t,i)=>{const n=i+1,status=n<3?'done':n===3?'current':n===4?'next':'locked',open=n===state.step;return `<article class="step ${status} ${open?'is-open':''}"><button data-step="${n}" ${status==='locked'?'disabled':''}><span class="step-no">${status==='done'?svg('check'):toFa(n)}</span><span><strong>${t}</strong><small>${i>7?'ایستگاه تثبیت':'ویدئو، جزوه و تمرین'}</small></span><em>${status==='current'?'قدم فعلی':status==='done'?'انجام‌شده':status==='next'?'بعدی':'قفل'}</em>${svg(status==='locked'?'lock':'chevron')}</button>${open?`<div class="resources"><div>${svg('video')}<span><strong>جلسه آموزشی</strong><small>۲۶ دقیقه</small></span><button>مشاهده</button></div><div>${svg('file')}<span><strong>جزوه مبحث</strong><small>PDF · ۱۸ صفحه</small></span><button>باز کردن</button></div></div>`:''}</article>`}).join('')}
function comprehensive(c){return `<div class="page chapter-page">${topbar(c.title,c.sub,'roadmap')}<section class="comprehensive-hero"><span>${svg('scale')}</span><div><small>ایستگاه ویژه مسیر</small><h2>${c.title}</h2><p>${c.sub} با آزمون ترکیبی و تحلیل نقاط ضعف</p></div><strong>${c.id===6?'۵':'۱۰'} فصل</strong></section><section class="review-map">${subjects.map((s,i)=>`<article><span>${toFa(i+1)}</span><div><strong>${s[0]}</strong><small>${subjectTopics[i][0]} و ${subjectTopics[i][1]}</small></div><button>${i<2?'ادامه':'شروع'}</button></article>`).join('')}</section></div>`}
function reviews(){return `<div class="page">${topbar('مرورهای آماده','بازیابی کوتاه و هدفمند','home')}<section class="compact-section"><div class="section-head"><div><span class="section-kicker">۳ مرور امروز</span><h2>بر اساس مطالعه‌های قبلی</h2></div></div><div class="review-grid">${reviewCards()}</div></section></div>`}
function progressView(){return `<div class="page">${topbar('گزارش پیشرفت','تصویر روشن از وضعیت هر درس','home')}<section class="progress-summary"><span>پیشرفت کل دوره</span><strong>${toFa(overall())}٪</strong><i><b style="width:${overall()}%"></b></i></section><section class="progress-list">${subjects.map(s=>`<article><span>${svg('scale')}</span><div><strong>${s[0]}</strong><small>${s[1]===100?'تکمیل‌شده':'ادامه قدم فعلی'}</small><i><b style="width:${s[1]}%"></b></i></div><em>${toFa(s[1])}٪</em></article>`).join('')}</section></div>`}
function render(){document.querySelectorAll('[data-route]').forEach(b=>b.classList.toggle('is-active',b.dataset.route===state.route));app.innerHTML=state.route==='home'?home():state.route==='roadmap'?roadmap():state.route==='chapter'?chapter():state.route==='reviews'?reviews():progressView();bind();app.focus({preventScroll:true})}
function bind(){document.querySelectorAll('[data-route]').forEach(b=>b.onclick=()=>{state.route=b.dataset.route;if(state.route==='roadmap')state.chapter=null;render()});document.querySelectorAll('[data-chapter]').forEach(b=>b.onclick=()=>{const id=+b.dataset.chapter,p=progress();if(id>p.unlocked){toast(`ابتدا ${chapterData[id-2]?.title||'مرحله قبل'} را تکمیل کن.`);return}state.chapter=id;state.subject=0;state.step=3;state.reviewed=[];state.route='chapter';render()});document.querySelectorAll('[data-subject]').forEach(b=>b.onclick=()=>{state.subject=+b.dataset.subject;state.step=3;render()});document.querySelectorAll('[data-step]').forEach(b=>b.onclick=()=>{state.step=+b.dataset.step;render()});document.querySelectorAll('[data-review]').forEach(b=>b.onclick=()=>{const id=+b.dataset.review;state.reviewed=state.reviewed.includes(id)?state.reviewed.filter(x=>x!==id):[...state.reviewed,id];if(state.reviewed.length===6){const saved=JSON.parse(localStorage.getItem('masirReviews')||'[]');if(!saved.includes(state.chapter))saved.push(state.chapter);localStorage.setItem('masirReviews',JSON.stringify(saved));setTimeout(render,280)}else render()});document.querySelectorAll('[data-open-menu]').forEach(b=>b.onclick=()=>document.getElementById('menuDialog').showModal())}
function toast(t){const e=document.getElementById('roadmapToast');e.textContent=t;e.classList.add('is-visible');setTimeout(()=>e.classList.remove('is-visible'),3000)}
document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>document.getElementById(b.dataset.close).close());
document.getElementById('supportFab').onclick=()=>document.getElementById('supportDialog').showModal();
document.getElementById('supportForm').onsubmit=e=>{e.preventDefault();const input=document.getElementById('supportInput');if(!input.value.trim())return;document.getElementById('supportMessages').insertAdjacentHTML('beforeend',`<div class="user-message">${input.value.replace(/[<>]/g,'')}</div><div class="bot-message">پیامت ثبت شد. پشتیبان مسیر بررسی می‌کند.</div>`);input.value=''};
document.getElementById('setupForm').onsubmit=e=>{e.preventDefault();localStorage.setItem('masirCourse',JSON.stringify({name:document.getElementById('courseInput').value}));document.getElementById('setupDialog').close();render()};
document.querySelectorAll('[data-edit-course]').forEach(b=>b.onclick=()=>{document.getElementById('menuDialog').close();document.getElementById('setupDialog').showModal()});
document.querySelectorAll('[data-theme-toggle]').forEach(b=>b.onclick=()=>{document.body.dataset.theme=document.body.dataset.theme==='light'?'dark':'light';localStorage.setItem('masirTheme',document.body.dataset.theme);render()});
document.getElementById('explainPage').onclick=()=>{document.getElementById('supportDialog').close();toast('راهنمای همین صفحه فعال شد؛ مرحله فعلی با نور آبی مشخص است.')};
const audioDucking=new AudioDuckingController({navigator,window});
document.querySelectorAll('audio[data-assistant-audio]').forEach(element=>audioDucking.trackMediaElement(element));
window.assistantAudioDucking={begin:()=>audioDucking.start(),track:element=>audioDucking.trackMediaElement(element),trackUtterance:utterance=>audioDucking.trackSpeechUtterance(utterance),stop:reason=>audioDucking.stopAll(reason||'cancelled'),get active(){return audioDucking.active},get mode(){return audioDucking.mode}};
document.body.dataset.theme=localStorage.getItem('masirTheme')||'dark';render();if(!localStorage.getItem('masirCourse')&&!new URLSearchParams(location.search).has('preview'))setTimeout(()=>document.getElementById('setupDialog').showModal(),400);
